CREATE foreign TABLE mangadapdb.c5_cstore_ssd (                            
     pk bigint  NULL,                                     
     file_pk integer  NULL,                               
     spaxel_index integer  NULL,                          
     binid_pk integer  NULL,                              
     spx_skycoo_on_sky_x real  NULL,                      
     spx_skycoo_on_sky_y real  NULL,                      
     spx_ellcoo_elliptical_radius real  NULL,             
     spx_ellcoo_elliptical_azimuth real  NULL,            
     spx_mflux real  NULL,                                
     spx_mflux_ivar double precision  NULL,               
     spx_snr real  NULL,                                  
     binid integer  NULL,                                 
     bin_lwskycoo_lum_weighted_on_sky_x real  NULL,       
     bin_lwskycoo_lum_weighted_on_sky_y real  NULL,       
     bin_lwellcoo_lum_weighted_elliptical_radius real  NULL,
     bin_lwellcoo_lum_weighted_elliptical_azimuth real  NULL,
     bin_area real  NULL,                                 
     bin_farea real  NULL,                                
     bin_mflux real  NULL,                                
     bin_mflux_ivar double precision  NULL,               
     bin_mflux_mask integer  NULL,                        
     bin_snr real  NULL,                                  
     stellar_vel real  NULL,                              
     stellar_vel_ivar double precision  NULL,             
     stellar_vel_mask integer  NULL,                      
     stellar_sigma real  NULL,                            
     stellar_sigma_ivar double precision  NULL,           
     stellar_sigma_mask integer  NULL,                    
     stellar_sigmacorr real  NULL,                        
     stellar_cont_fresid_68th_percentile real  NULL,      
     stellar_cont_fresid_99th_percentile real  NULL,      
     stellar_cont_rchi2 real  NULL,                       
     emline_sflux_oiid_3728 real  NULL,                   
     emline_sflux_hb_4862 real  NULL,                     
     emline_sflux_oiii_4960 real  NULL,                   
     emline_sflux_oiii_5008 real  NULL,                   
     emline_sflux_oi_6302 real  NULL,                     
     emline_sflux_oi_6365 real  NULL,                     
     emline_sflux_nii_6549 real  NULL,                    
     emline_sflux_ha_6564 real  NULL,                     
     emline_sflux_nii_6585 real  NULL,                    
     emline_sflux_sii_6718 real  NULL,                    
     emline_sflux_sii_6732 real  NULL,                    
     emline_sflux_oii_3727 real  NULL,                    
     emline_sflux_oii_3729 real  NULL,                    
     emline_sflux_heps_3971 real  NULL,                   
     emline_sflux_hdel_4102 real  NULL,                   
     emline_sflux_hgam_4341 real  NULL,                   
     emline_sflux_heii_4687 real  NULL,                   
     emline_sflux_hei_5877 real  NULL,                    
     emline_sflux_siii_8831 real  NULL,                   
     emline_sflux_siii_9071 real  NULL,                   
     emline_sflux_siii_9533 real  NULL,                   
     emline_sflux_ivar_oiid_3728 double precision  NULL,  
     emline_sflux_ivar_hb_4862 double precision  NULL,    
     emline_sflux_ivar_oiii_4960 double precision  NULL,  
     emline_sflux_ivar_oiii_5008 double precision  NULL,  
     emline_sflux_ivar_oi_6302 double precision  NULL,    
     emline_sflux_ivar_oi_6365 double precision  NULL,    
     emline_sflux_ivar_nii_6549 double precision  NULL,   
     emline_sflux_ivar_ha_6564 double precision  NULL,    
     emline_sflux_ivar_nii_6585 double precision  NULL,   
     emline_sflux_ivar_sii_6718 double precision  NULL,   
     emline_sflux_ivar_sii_6732 double precision  NULL,   
     emline_sflux_ivar_oii_3727 double precision  NULL,   
     emline_sflux_ivar_oii_3729 double precision  NULL,   
     emline_sflux_ivar_heps_3971 double precision  NULL,  
     emline_sflux_ivar_hdel_4102 double precision  NULL,  
     emline_sflux_ivar_hgam_4341 double precision  NULL,  
     emline_sflux_ivar_heii_4687 double precision  NULL,  
     emline_sflux_ivar_hei_5877 double precision  NULL,   
     emline_sflux_ivar_siii_8831 double precision  NULL,  
     emline_sflux_ivar_siii_9071 double precision  NULL,  
     emline_sflux_ivar_siii_9533 double precision  NULL,  
     emline_sflux_mask_oiid_3728 integer  NULL,           
     emline_sflux_mask_hb_4862 integer  NULL,             
     emline_sflux_mask_oiii_4960 integer  NULL,           
     emline_sflux_mask_oiii_5008 integer  NULL,           
     emline_sflux_mask_oi_6302 integer  NULL,             
     emline_sflux_mask_oi_6365 integer  NULL,             
     emline_sflux_mask_nii_6549 integer  NULL,            
     emline_sflux_mask_ha_6564 integer  NULL,             
     emline_sflux_mask_nii_6585 integer  NULL,            
     emline_sflux_mask_sii_6718 integer  NULL,            
     emline_sflux_mask_sii_6732 integer  NULL,            
     emline_sflux_mask_oii_3727 integer  NULL,            
     emline_sflux_mask_oii_3729 integer  NULL,            
     emline_sflux_mask_heps_3971 integer  NULL,           
     emline_sflux_mask_hdel_4102 integer  NULL,           
     emline_sflux_mask_hgam_4341 integer  NULL,           
     emline_sflux_mask_heii_4687 integer  NULL,           
     emline_sflux_mask_hei_5877 integer  NULL,            
     emline_sflux_mask_siii_8831 integer  NULL,           
     emline_sflux_mask_siii_9071 integer  NULL,           
     emline_sflux_mask_siii_9533 integer  NULL,           
     emline_sew_oiid_3728 double precision  NULL,         
     emline_sew_hb_4862 double precision  NULL,           
     emline_sew_oiii_4960 double precision  NULL,         
     emline_sew_oiii_5008 double precision  NULL,         
     emline_sew_oi_6302 double precision  NULL,           
     emline_sew_oi_6365 double precision  NULL,           
     emline_sew_nii_6549 double precision  NULL,          
     emline_sew_ha_6564 double precision  NULL,           
     emline_sew_nii_6585 double precision  NULL,          
     emline_sew_sii_6718 double precision  NULL,          
     emline_sew_sii_6732 double precision  NULL,          
     emline_sew_oii_3727 double precision  NULL,          
     emline_sew_oii_3729 double precision  NULL,          
     emline_sew_heps_3971 double precision  NULL,         
     emline_sew_hdel_4102 double precision  NULL,         
     emline_sew_hgam_4341 double precision  NULL,         
     emline_sew_heii_4687 double precision  NULL,         
     emline_sew_hei_5877 double precision  NULL,          
     emline_sew_siii_8831 double precision  NULL,         
     emline_sew_siii_9071 double precision  NULL,         
     emline_sew_siii_9533 double precision  NULL,         
     emline_sew_ivar_oiid_3728 double precision  NULL,    
     emline_sew_ivar_hb_4862 double precision  NULL,      
     emline_sew_ivar_oiii_4960 double precision  NULL,    
     emline_sew_ivar_oiii_5008 double precision  NULL,    
     emline_sew_ivar_oi_6302 double precision  NULL,      
     emline_sew_ivar_oi_6365 double precision  NULL,      
     emline_sew_ivar_nii_6549 double precision  NULL,     
     emline_sew_ivar_ha_6564 double precision  NULL,      
     emline_sew_ivar_nii_6585 double precision  NULL,     
     emline_sew_ivar_sii_6718 double precision  NULL,     
     emline_sew_ivar_sii_6732 double precision  NULL,     
     emline_sew_ivar_oii_3727 double precision  NULL,     
     emline_sew_ivar_oii_3729 double precision  NULL,     
     emline_sew_ivar_heps_3971 double precision  NULL,    
     emline_sew_ivar_hdel_4102 double precision  NULL,    
     emline_sew_ivar_hgam_4341 double precision  NULL,    
     emline_sew_ivar_heii_4687 double precision  NULL,    
     emline_sew_ivar_hei_5877 double precision  NULL,     
     emline_sew_ivar_siii_8831 double precision  NULL,    
     emline_sew_ivar_siii_9071 double precision  NULL,    
     emline_sew_ivar_siii_9533 double precision  NULL,    
     emline_sew_mask_oiid_3728 integer  NULL,             
     emline_sew_mask_hb_4862 integer  NULL,               
     emline_sew_mask_oiii_4960 integer  NULL,             
     emline_sew_mask_oiii_5008 integer  NULL,             
     emline_sew_mask_oi_6302 integer  NULL,               
     emline_sew_mask_oi_6365 integer  NULL,               
     emline_sew_mask_nii_6549 integer  NULL,              
     emline_sew_mask_ha_6564 integer  NULL,               
     emline_sew_mask_nii_6585 integer  NULL,              
     emline_sew_mask_sii_6718 integer  NULL,              
     emline_sew_mask_sii_6732 integer  NULL,              
     emline_sew_mask_oii_3727 integer  NULL,              
     emline_sew_mask_oii_3729 integer  NULL,              
     emline_sew_mask_heps_3971 integer  NULL,             
     emline_sew_mask_hdel_4102 integer  NULL,             
     emline_sew_mask_hgam_4341 integer  NULL,             
     emline_sew_mask_heii_4687 integer  NULL,             
     emline_sew_mask_hei_5877 integer  NULL,              
     emline_sew_mask_siii_8831 integer  NULL,             
     emline_sew_mask_siii_9071 integer  NULL,             
     emline_sew_mask_siii_9533 integer  NULL,             
     emline_gflux_oiid_3728 real  NULL,                   
     emline_gflux_hb_4862 real  NULL,                     
     emline_gflux_oiii_4960 real  NULL,                   
     emline_gflux_oiii_5008 double precision  NULL,       
     emline_gflux_oi_6302 real  NULL,                     
     emline_gflux_oi_6365 real  NULL,                     
     emline_gflux_nii_6549 real  NULL,                    
     emline_gflux_ha_6564 double precision  NULL,         
     emline_gflux_nii_6585 double precision  NULL,        
     emline_gflux_sii_6718 real  NULL,                    
     emline_gflux_sii_6732 double precision  NULL,        
     emline_gflux_oii_3727 double precision  NULL,        
     emline_gflux_oii_3729 real  NULL,                    
     emline_gflux_heps_3971 real  NULL,                   
     emline_gflux_hdel_4102 real  NULL,                   
     emline_gflux_hgam_4341 real  NULL,                   
     emline_gflux_heii_4687 real  NULL,                   
     emline_gflux_hei_5877 real  NULL,                    
     emline_gflux_siii_8831 real  NULL,                   
     emline_gflux_siii_9071 real  NULL,                   
     emline_gflux_siii_9533 real  NULL,                   
     emline_gflux_ivar_oiid_3728 double precision  NULL,  
     emline_gflux_ivar_hb_4862 double precision  NULL,    
     emline_gflux_ivar_oiii_4960 double precision  NULL,  
     emline_gflux_ivar_oiii_5008 double precision  NULL,  
     emline_gflux_ivar_oi_6302 double precision  NULL,    
     emline_gflux_ivar_oi_6365 double precision  NULL,    
     emline_gflux_ivar_nii_6549 double precision  NULL,   
     emline_gflux_ivar_ha_6564 double precision  NULL,    
     emline_gflux_ivar_nii_6585 double precision  NULL,   
     emline_gflux_ivar_sii_6718 double precision  NULL,   
     emline_gflux_ivar_sii_6732 double precision  NULL,   
     emline_gflux_ivar_oii_3727 double precision  NULL,   
     emline_gflux_ivar_oii_3729 double precision  NULL,   
     emline_gflux_ivar_heps_3971 double precision  NULL,  
     emline_gflux_ivar_hdel_4102 double precision  NULL,  
     emline_gflux_ivar_hgam_4341 double precision  NULL,  
     emline_gflux_ivar_heii_4687 double precision  NULL,  
     emline_gflux_ivar_hei_5877 double precision  NULL,   
     emline_gflux_ivar_siii_8831 double precision  NULL,  
     emline_gflux_ivar_siii_9071 double precision  NULL,  
     emline_gflux_ivar_siii_9533 double precision  NULL,  
     emline_gflux_mask_oiid_3728 integer  NULL,           
     emline_gflux_mask_hb_4862 integer  NULL,             
     emline_gflux_mask_oiii_4960 integer  NULL,           
     emline_gflux_mask_oiii_5008 integer  NULL,           
     emline_gflux_mask_oi_6302 integer  NULL,             
     emline_gflux_mask_oi_6365 integer  NULL,             
     emline_gflux_mask_nii_6549 integer  NULL,            
     emline_gflux_mask_ha_6564 integer  NULL,             
     emline_gflux_mask_nii_6585 integer  NULL,            
     emline_gflux_mask_sii_6718 integer  NULL,            
     emline_gflux_mask_sii_6732 integer  NULL,            
     emline_gflux_mask_oii_3727 integer  NULL,            
     emline_gflux_mask_oii_3729 integer  NULL,            
     emline_gflux_mask_heps_3971 integer  NULL,           
     emline_gflux_mask_hdel_4102 integer  NULL,           
     emline_gflux_mask_hgam_4341 integer  NULL,           
     emline_gflux_mask_heii_4687 integer  NULL,           
     emline_gflux_mask_hei_5877 integer  NULL,            
     emline_gflux_mask_siii_8831 integer  NULL,           
     emline_gflux_mask_siii_9071 integer  NULL,           
     emline_gflux_mask_siii_9533 integer  NULL,           
     emline_gvel_oiid_3728 real  NULL,                    
     emline_gvel_hb_4862 real  NULL,                      
     emline_gvel_oiii_4960 real  NULL,                    
     emline_gvel_oiii_5008 real  NULL,                    
     emline_gvel_oi_6302 real  NULL,                      
     emline_gvel_oi_6365 real  NULL,                      
     emline_gvel_nii_6549 real  NULL,                     
     emline_gvel_ha_6564 real  NULL,                      
     emline_gvel_nii_6585 real  NULL,                     
     emline_gvel_sii_6718 real  NULL,                     
     emline_gvel_sii_6732 real  NULL,                     
     emline_gvel_oii_3727 real  NULL,                     
     emline_gvel_oii_3729 real  NULL,                     
     emline_gvel_heps_3971 real  NULL,                    
     emline_gvel_hdel_4102 real  NULL,                    
     emline_gvel_hgam_4341 real  NULL,                    
     emline_gvel_heii_4687 real  NULL,                    
     emline_gvel_hei_5877 real  NULL,                     
     emline_gvel_siii_8831 real  NULL,                    
     emline_gvel_siii_9071 real  NULL,                    
     emline_gvel_siii_9533 real  NULL,                    
     emline_gvel_ivar_oiid_3728 double precision  NULL,   
     emline_gvel_ivar_hb_4862 double precision  NULL,     
     emline_gvel_ivar_oiii_4960 double precision  NULL,   
     emline_gvel_ivar_oiii_5008 double precision  NULL,   
     emline_gvel_ivar_oi_6302 double precision  NULL,     
     emline_gvel_ivar_oi_6365 double precision  NULL,     
     emline_gvel_ivar_nii_6549 double precision  NULL,    
     emline_gvel_ivar_ha_6564 double precision  NULL,     
     emline_gvel_ivar_nii_6585 double precision  NULL,    
     emline_gvel_ivar_sii_6718 double precision  NULL,    
     emline_gvel_ivar_sii_6732 double precision  NULL,    
     emline_gvel_ivar_oii_3727 double precision  NULL,    
     emline_gvel_ivar_oii_3729 double precision  NULL,    
     emline_gvel_ivar_heps_3971 double precision  NULL,   
     emline_gvel_ivar_hdel_4102 double precision  NULL,   
     emline_gvel_ivar_hgam_4341 double precision  NULL,   
     emline_gvel_ivar_heii_4687 double precision  NULL,   
     emline_gvel_ivar_hei_5877 double precision  NULL,    
     emline_gvel_ivar_siii_8831 double precision  NULL,   
     emline_gvel_ivar_siii_9071 double precision  NULL,   
     emline_gvel_ivar_siii_9533 double precision  NULL,   
     emline_gvel_mask_oiid_3728 integer  NULL,            
     emline_gvel_mask_hb_4862 integer  NULL,              
     emline_gvel_mask_oiii_4960 integer  NULL,            
     emline_gvel_mask_oiii_5008 integer  NULL,            
     emline_gvel_mask_oi_6302 integer  NULL,              
     emline_gvel_mask_oi_6365 integer  NULL,              
     emline_gvel_mask_nii_6549 integer  NULL,             
     emline_gvel_mask_ha_6564 integer  NULL,              
     emline_gvel_mask_nii_6585 integer  NULL,             
     emline_gvel_mask_sii_6718 integer  NULL,             
     emline_gvel_mask_sii_6732 integer  NULL,             
     emline_gvel_mask_oii_3727 integer  NULL,             
     emline_gvel_mask_oii_3729 integer  NULL,             
     emline_gvel_mask_heps_3971 integer  NULL,            
     emline_gvel_mask_hdel_4102 integer  NULL,            
     emline_gvel_mask_hgam_4341 integer  NULL,            
     emline_gvel_mask_heii_4687 integer  NULL,            
     emline_gvel_mask_hei_5877 integer  NULL,             
     emline_gvel_mask_siii_8831 integer  NULL,            
     emline_gvel_mask_siii_9071 integer  NULL,            
     emline_gvel_mask_siii_9533 integer  NULL,            
     emline_gsigma_oiid_3728 real  NULL,                  
     emline_gsigma_hb_4862 real  NULL,                    
     emline_gsigma_oiii_4960 real  NULL,                  
     emline_gsigma_oiii_5008 real  NULL,                  
     emline_gsigma_oi_6302 real  NULL,                    
     emline_gsigma_oi_6365 real  NULL,                    
     emline_gsigma_nii_6549 real  NULL,                   
     emline_gsigma_ha_6564 real  NULL,                    
     emline_gsigma_nii_6585 real  NULL,                   
     emline_gsigma_sii_6718 real  NULL,                   
     emline_gsigma_sii_6732 real  NULL,                   
     emline_gsigma_oii_3727 real  NULL,                   
     emline_gsigma_oii_3729 real  NULL,                   
     emline_gsigma_heps_3971 real  NULL,                  
     emline_gsigma_hdel_4102 real  NULL,                  
     emline_gsigma_hgam_4341 real  NULL,                  
     emline_gsigma_heii_4687 real  NULL,                  
     emline_gsigma_hei_5877 real  NULL,                   
     emline_gsigma_siii_8831 real  NULL,                  
     emline_gsigma_siii_9071 real  NULL,                  
     emline_gsigma_siii_9533 real  NULL,                  
     emline_gsigma_ivar_oiid_3728 double precision  NULL, 
     emline_gsigma_ivar_hb_4862 double precision  NULL,   
     emline_gsigma_ivar_oiii_4960 double precision  NULL, 
     emline_gsigma_ivar_oiii_5008 double precision  NULL, 
     emline_gsigma_ivar_oi_6302 double precision  NULL,   
     emline_gsigma_ivar_oi_6365 double precision  NULL,   
     emline_gsigma_ivar_nii_6549 double precision  NULL,  
     emline_gsigma_ivar_ha_6564 double precision  NULL,   
     emline_gsigma_ivar_nii_6585 double precision  NULL,  
     emline_gsigma_ivar_sii_6718 double precision  NULL,  
     emline_gsigma_ivar_sii_6732 double precision  NULL,  
     emline_gsigma_ivar_oii_3727 double precision  NULL,  
     emline_gsigma_ivar_oii_3729 double precision  NULL,  
     emline_gsigma_ivar_heps_3971 double precision  NULL, 
     emline_gsigma_ivar_hdel_4102 double precision  NULL, 
     emline_gsigma_ivar_hgam_4341 double precision  NULL, 
     emline_gsigma_ivar_heii_4687 double precision  NULL, 
     emline_gsigma_ivar_hei_5877 double precision  NULL,  
     emline_gsigma_ivar_siii_8831 double precision  NULL, 
     emline_gsigma_ivar_siii_9071 double precision  NULL, 
     emline_gsigma_ivar_siii_9533 double precision  NULL, 
     emline_gsigma_mask_oiid_3728 integer  NULL,          
     emline_gsigma_mask_hb_4862 integer  NULL,            
     emline_gsigma_mask_oiii_4960 integer  NULL,          
     emline_gsigma_mask_oiii_5008 integer  NULL,          
     emline_gsigma_mask_oi_6302 integer  NULL,            
     emline_gsigma_mask_oi_6365 integer  NULL,            
     emline_gsigma_mask_nii_6549 integer  NULL,           
     emline_gsigma_mask_ha_6564 integer  NULL,            
     emline_gsigma_mask_nii_6585 integer  NULL,           
     emline_gsigma_mask_sii_6718 integer  NULL,           
     emline_gsigma_mask_sii_6732 integer  NULL,           
     emline_gsigma_mask_oii_3727 integer  NULL,           
     emline_gsigma_mask_oii_3729 integer  NULL,           
     emline_gsigma_mask_heps_3971 integer  NULL,          
     emline_gsigma_mask_hdel_4102 integer  NULL,          
     emline_gsigma_mask_hgam_4341 integer  NULL,          
     emline_gsigma_mask_heii_4687 integer  NULL,          
     emline_gsigma_mask_hei_5877 integer  NULL,           
     emline_gsigma_mask_siii_8831 integer  NULL,          
     emline_gsigma_mask_siii_9071 integer  NULL,          
     emline_gsigma_mask_siii_9533 integer  NULL,          
     emline_instsigma_oiid_3728 real  NULL,               
     emline_instsigma_hb_4862 real  NULL,                 
     emline_instsigma_oiii_4960 real  NULL,               
     emline_instsigma_oiii_5008 real  NULL,               
     emline_instsigma_oi_6302 real  NULL,                 
     emline_instsigma_oi_6365 real  NULL,                 
     emline_instsigma_nii_6549 real  NULL,                
     emline_instsigma_ha_6564 real  NULL,                 
     emline_instsigma_nii_6585 real  NULL,                
     emline_instsigma_sii_6718 real  NULL,                
     emline_instsigma_sii_6732 real  NULL,                
     emline_instsigma_oii_3727 real  NULL,                
     emline_instsigma_oii_3729 real  NULL,                
     emline_instsigma_heps_3971 real  NULL,               
     emline_instsigma_hdel_4102 real  NULL,               
     emline_instsigma_hgam_4341 real  NULL,               
     emline_instsigma_heii_4687 real  NULL,               
     emline_instsigma_hei_5877 real  NULL,                
     emline_instsigma_siii_8831 real  NULL,               
     emline_instsigma_siii_9071 real  NULL,               
     emline_instsigma_siii_9533 real  NULL,               
     specindex_d4000 real  NULL,                          
     specindex_dn4000 real  NULL,                         
     specindex_ivar_d4000 double precision  NULL,         
     specindex_ivar_dn4000 double precision  NULL,        
     specindex_mask_d4000 integer  NULL,                  
     specindex_mask_dn4000 integer  NULL,                 
     specindex_corr_d4000 real  NULL,                     
     specindex_corr_dn4000 real  NULL,                    
     x integer  NULL,                                     
     y integer  NULL)
     server cstore_server
     options(filename '/ssd/postgres_db/manga/c5_ssd_cstore.cstore', compression 'pglz');
     
     insert into c5_cstore_ssd
     select * from c5_ssd;
     
     
     analyze mangadapdb.c5_cstore_ssd;
     
     alter table mangadapdb.c5_cstore_ssd set owner manga;
     
     
     
